// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/iqbal2604/dear-talk-api.git/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MessageUsecase is an autogenerated mock type for the MessageUsecase type
type MessageUsecase struct {
	mock.Mock
}

// DeleteMessage provides a mock function with given fields: userID, messageID
func (_m *MessageUsecase) DeleteMessage(userID uint, messageID uint) error {
	ret := _m.Called(userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditMessage provides a mock function with given fields: userID, messageID, req
func (_m *MessageUsecase) EditMessage(userID uint, messageID uint, req *domain.EditMessageRequest) (*domain.Message, error) {
	ret := _m.Called(userID, messageID, req)

	if len(ret) == 0 {
		panic("no return value specified for EditMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.EditMessageRequest) (*domain.Message, error)); ok {
		return rf(userID, messageID, req)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.EditMessageRequest) *domain.Message); ok {
		r0 = rf(userID, messageID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint, *domain.EditMessageRequest) error); ok {
		r1 = rf(userID, messageID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: userID, roomID, page, limit
func (_m *MessageUsecase) GetMessages(userID uint, roomID uint, page int, limit int) ([]*domain.Message, int64, error) {
	ret := _m.Called(userID, roomID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*domain.Message
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, uint, int, int) ([]*domain.Message, int64, error)); ok {
		return rf(userID, roomID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, int, int) []*domain.Message); ok {
		r0 = rf(userID, roomID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint, int, int) int64); ok {
		r1 = rf(userID, roomID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, uint, int, int) error); ok {
		r2 = rf(userID, roomID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkAsRead provides a mock function with given fields: userID, roomID
func (_m *MessageUsecase) MarkAsRead(userID uint, roomID uint) error {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessage provides a mock function with given fields: userID, roomID, req
func (_m *MessageUsecase) SendMessage(userID uint, roomID uint, req *domain.SendMessageRequest) (*domain.Message, error) {
	ret := _m.Called(userID, roomID, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.SendMessageRequest) (*domain.Message, error)); ok {
		return rf(userID, roomID, req)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.SendMessageRequest) *domain.Message); ok {
		r0 = rf(userID, roomID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint, *domain.SendMessageRequest) error); ok {
		r1 = rf(userID, roomID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageUsecase creates a new instance of MessageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageUsecase {
	mock := &MessageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
