// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/iqbal2604/dear-talk-api.git/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoomRepository is an autogenerated mock type for the RoomRepository type
type RoomRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: member
func (_m *RoomRepository) AddMember(member *domain.RoomMember) error {
	ret := _m.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RoomMember) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: room
func (_m *RoomRepository) Create(room *domain.Room) error {
	ret := _m.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Room) error); ok {
		r0 = rf(room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *RoomRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *RoomRepository) FindByID(id uint) (*domain.Room, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Room, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Room); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: userID
func (_m *RoomRepository) FindByUserID(userID uint) ([]*domain.Room, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*domain.Room, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*domain.Room); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMember provides a mock function with given fields: roomID, userID
func (_m *RoomRepository) FindMember(roomID uint, userID uint) (*domain.RoomMember, error) {
	ret := _m.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindMember")
	}

	var r0 *domain.RoomMember
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*domain.RoomMember, error)); ok {
		return rf(roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *domain.RoomMember); ok {
		r0 = rf(roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RoomMember)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: roomID, userID
func (_m *RoomRepository) RemoveMember(roomID uint, userID uint) error {
	ret := _m.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: room
func (_m *RoomRepository) Update(room *domain.Room) error {
	ret := _m.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Room) error); ok {
		r0 = rf(room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomRepository creates a new instance of RoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepository {
	mock := &RoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
