// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/iqbal2604/dear-talk-api.git/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoomUsecase is an autogenerated mock type for the RoomUsecase type
type RoomUsecase struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: userID, roomID, req
func (_m *RoomUsecase) AddMember(userID uint, roomID uint, req *domain.AddMemberRequest) error {
	ret := _m.Called(userID, roomID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.AddMemberRequest) error); ok {
		r0 = rf(userID, roomID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRoom provides a mock function with given fields: userID, req
func (_m *RoomUsecase) CreateRoom(userID uint, req *domain.CreateRoomRequest) (*domain.Room, error) {
	ret := _m.Called(userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *domain.CreateRoomRequest) (*domain.Room, error)); ok {
		return rf(userID, req)
	}
	if rf, ok := ret.Get(0).(func(uint, *domain.CreateRoomRequest) *domain.Room); ok {
		r0 = rf(userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *domain.CreateRoomRequest) error); ok {
		r1 = rf(userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRoom provides a mock function with given fields: userID, roomID
func (_m *RoomUsecase) DeleteRoom(userID uint, roomID uint) error {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoomByID provides a mock function with given fields: userID, roomID
func (_m *RoomUsecase) GetRoomByID(userID uint, roomID uint) (*domain.Room, error) {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*domain.Room, error)); ok {
		return rf(userID, roomID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *domain.Room); ok {
		r0 = rf(userID, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(userID, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRooms provides a mock function with given fields: userID
func (_m *RoomUsecase) GetRooms(userID uint) ([]*domain.Room, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 []*domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*domain.Room, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*domain.Room); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: userID, roomID, targetUserID
func (_m *RoomUsecase) RemoveMember(userID uint, roomID uint, targetUserID uint) error {
	ret := _m.Called(userID, roomID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, uint) error); ok {
		r0 = rf(userID, roomID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoom provides a mock function with given fields: userID, roomID, req
func (_m *RoomUsecase) UpdateRoom(userID uint, roomID uint, req *domain.UpdateRoomRequest) (*domain.Room, error) {
	ret := _m.Called(userID, roomID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.UpdateRoomRequest) (*domain.Room, error)); ok {
		return rf(userID, roomID, req)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, *domain.UpdateRoomRequest) *domain.Room); ok {
		r0 = rf(userID, roomID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint, *domain.UpdateRoomRequest) error); ok {
		r1 = rf(userID, roomID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomUsecase creates a new instance of RoomUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomUsecase {
	mock := &RoomUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
