// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenBlacklist is an autogenerated mock type for the TokenBlacklist type
type TokenBlacklist struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, token, expiry
func (_m *TokenBlacklist) Add(ctx context.Context, token string, expiry time.Duration) error {
	ret := _m.Called(ctx, token, expiry)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, token, expiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsBlacklisted provides a mock function with given fields: ctx, token
func (_m *TokenBlacklist) IsBlacklisted(ctx context.Context, token string) (bool, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenBlacklist creates a new instance of TokenBlacklist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenBlacklist(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenBlacklist {
	mock := &TokenBlacklist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
