// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/iqbal2604/dear-talk-api.git/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserManagementUsecase is an autogenerated mock type for the UserManagementUsecase type
type UserManagementUsecase struct {
	mock.Mock
}

// GetProfile provides a mock function with given fields: id
func (_m *UserManagementUsecase) GetProfile(id uint) (*domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: id
func (_m *UserManagementUsecase) GetUserByID(id uint) (*domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUsers provides a mock function with given fields: query
func (_m *UserManagementUsecase) SearchUsers(query string) ([]*domain.User, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.User, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.User); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: id, req
func (_m *UserManagementUsecase) UpdateProfile(id uint, req *domain.UpdateProfileRequest) (*domain.User, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *domain.UpdateProfileRequest) (*domain.User, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uint, *domain.UpdateProfileRequest) *domain.User); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *domain.UpdateProfileRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserManagementUsecase creates a new instance of UserManagementUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserManagementUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserManagementUsecase {
	mock := &UserManagementUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
