// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/iqbal2604/dear-talk-api.git/internal/domain"
	"github.com/iqbal2604/dear-talk-api.git/internal/handler"
	"github.com/iqbal2604/dear-talk-api.git/internal/middleware"
	"github.com/iqbal2604/dear-talk-api.git/internal/repository"
	"github.com/iqbal2604/dear-talk-api.git/internal/usecase"
	"github.com/iqbal2604/dear-talk-api.git/internal/websocket"
	"github.com/iqbal2604/dear-talk-api.git/pkg/config"
	"github.com/iqbal2604/dear-talk-api.git/pkg/database"
	"github.com/iqbal2604/dear-talk-api.git/pkg/jwt"
	"github.com/iqbal2604/dear-talk-api.git/pkg/redis"
	redis2 "github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, log *zap.Logger) (*App, error) {
	databaseConfig := &cfg.Database
	db, err := database.NewPostgresConnection(databaseConfig, log)
	if err != nil {
		return nil, err
	}
	redisConfig := &cfg.Redis
	client, err := redis.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	jwtConfig := &cfg.JWT
	jwtUtil := jwt.NewJWTUtil(jwtConfig)
	tokenBlacklist := redis.NewTokenBlacklist(client)
	userUsecase := usecase.NewAuthUsecase(userRepository, jwtUtil, tokenBlacklist)
	authHandler := handler.NewAuthHandler(userUsecase)
	userManagementUsecase := usecase.NewUserManagementUsecase(userRepository)
	userHandler := handler.NewUserHandler(userManagementUsecase)
	roomRepository := repository.NewRoomRepository(db)
	roomUsecase := usecase.NewRoomUsecase(roomRepository, userRepository)
	roomHandler := handler.NewRoomHandler(roomUsecase)
	messageRepository := repository.NewMessageRepository(db)
	messageUsecase := usecase.NewMessageUsecase(messageRepository, roomRepository)
	messageHandler := handler.NewMessageHandler(messageUsecase)
	hub := websocket.NewHub()
	wsHandler := websocket.NewWSHandler(hub, jwtUtil, roomRepository, messageRepository, log)
	authMiddleware := middleware.NewAuthMiddleware(jwtUtil, tokenBlacklist)
	app := NewApp(db, client, authHandler, userHandler, roomHandler, messageHandler, wsHandler, authMiddleware)
	return app, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(database.NewPostgresConnection, jwt.NewJWTUtil, redis.NewRedisClient, redis.NewTokenBlacklist, wire.Bind(new(domain.TokenBlacklist), new(*redis.TokenBlacklist)))

var repositorySet = wire.NewSet(repository.NewUserRepository, repository.NewRoomRepository, repository.NewMessageRepository)

var usecaseSet = wire.NewSet(usecase.NewAuthUsecase, usecase.NewUserManagementUsecase, usecase.NewRoomUsecase, usecase.NewMessageUsecase)

var handlerSet = wire.NewSet(handler.NewAuthHandler, handler.NewUserHandler, handler.NewRoomHandler, handler.NewMessageHandler)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

var websocketSet = wire.NewSet(websocket.NewHub, websocket.NewWSHandler)

type App struct {
	DB             *gorm.DB
	Redis          *redis2.Client
	AuthHandler    *handler.AuthHandler
	UserHandler    *handler.UserHandler
	RoomHandler    *handler.RoomHandler
	AuthMiddleware *middleware.AuthMiddleware
	WSHandler      *websocket.WSHandler
	MessageHandler *handler.MessageHandler
}

func NewApp(
	db *gorm.DB,
	redisClient *redis2.Client,
	authHandler *handler.AuthHandler,
	userHandler *handler.UserHandler,
	roomHandler *handler.RoomHandler,
	messageHandler *handler.MessageHandler,
	wsHandler *websocket.WSHandler,
	authMiddleware *middleware.AuthMiddleware,
) *App {
	return &App{
		DB:             db,
		Redis:          redisClient,
		AuthHandler:    authHandler,
		UserHandler:    userHandler,
		RoomHandler:    roomHandler,
		MessageHandler: messageHandler,
		WSHandler:      wsHandler,
		AuthMiddleware: authMiddleware,
	}
}
