// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/iqbal2604/dear-talk-api.git/internal/handler"
	"github.com/iqbal2604/dear-talk-api.git/internal/middleware"
	"github.com/iqbal2604/dear-talk-api.git/internal/repository"
	"github.com/iqbal2604/dear-talk-api.git/internal/usecase"
	"github.com/iqbal2604/dear-talk-api.git/pkg/config"
	"github.com/iqbal2604/dear-talk-api.git/pkg/database"
	"github.com/iqbal2604/dear-talk-api.git/pkg/jwt"
	"github.com/iqbal2604/dear-talk-api.git/pkg/redis"
	redis2 "github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, log *zap.Logger) (*App, error) {
	databaseConfig := &cfg.Database
	db, err := database.NewPostgresConnection(databaseConfig, log)
	if err != nil {
		return nil, err
	}
	redisConfig := &cfg.Redis
	client, err := redis.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	jwtConfig := &cfg.JWT
	jwtUtil := jwt.NewJWTUtil(jwtConfig)
	userUsecase := usecase.NewAuthUsecase(userRepository, jwtUtil)
	authHandler := handler.NewAuthHandler(userUsecase)
	authMiddleware := middleware.NewAuthMiddleware(jwtUtil)
	app := NewApp(db, client, authHandler, authMiddleware)
	return app, nil
}

// wire.go:

// ─── Provider Sets ────────────────────────────────────────────────────────────
var infrastructureSet = wire.NewSet(database.NewPostgresConnection, jwt.NewJWTUtil, redis.NewRedisClient)

var repositorySet = wire.NewSet(repository.NewUserRepository)

var usecaseSet = wire.NewSet(usecase.NewAuthUsecase)

var handlerSet = wire.NewSet(handler.NewAuthHandler)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

type App struct {
	DB             *gorm.DB
	Redis          *redis2.Client
	AuthHandler    *handler.AuthHandler
	AuthMiddleware *middleware.AuthMiddleware
}

func NewApp(
	db *gorm.DB,
	redisClient *redis2.Client,
	authHandler *handler.AuthHandler,
	authMiddleware *middleware.AuthMiddleware,
) *App {
	return &App{
		DB:             db,
		Redis:          redisClient,
		AuthHandler:    authHandler,
		AuthMiddleware: authMiddleware,
	}
}
